task-1
alisherbazhenov/calorie-content pull request #1
Opened 2023-11-27 18:22 UTC by alisherbazhenov

1. Создал проект с помощью https://create-react-app.dev/docs/getting-started
2. Залил дефолтный проект на репозиторий.
3. Создал ветку main-page
4. Сделал главную страницу

2023-11-28 09:17 UTC, pavlenkovit requested changes

2023-11-28 09:17 UTC, pavlenkovit commented on src/components/Footer.jsx
> +		<footer className="footer">
Пусть все стили компонента лежат рядом с компонентом. Используй для этого CSS модули. У тебя тогда будет файлик Footer.module.css и там все стили

Вот здесь прочитай про это https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

2023-11-28 09:17 UTC, pavlenkovit commented on src/components/Footer.jsx
> +			<ul className="footer__list">
Когда ты затащишь css модули, то тебе больше не нужен будет БЭМ. Ты просто напишешь такие стили 

Footer.module.css
```css
.list {
}

.item {
}
```

Потом посмотришь в браузере на классы, они будут с уникальным хэшем для каждого компонента. То есть ты можешь в каждом компоненте делать класс .item

2023-11-28 09:17 UTC, pavlenkovit commented on src/components/Footer.jsx
> +							height="512"
Ты можешь в стилях не писать 24, а прям здесь указать размер

```suggestion
							width="24"
							height="24"
```

2023-11-28 09:17 UTC, pavlenkovit commented on src/components/Footer.jsx
> +						<svg
У тебя же уже лежат эти иконки в public. Можно их здесь использовать

https://stackoverflow.com/questions/59105148/react-svg-from-public-folder

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +	padding-left: 20px;
Для такого используем короткий формат

```suggestion
	padding: 0 20px;
```

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +	height: 100vh;
Сноси все эти стили. Флекс здесь не нужен, у тебя и так все элементы встраиваются вертикально друг за другом. И высота тоже не нужно. Это нормально, что контент переполняет страницу, а футер и так стики будет снизу

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +	position: relative;
relative не неужно. Убираем. У тебя же нет абсолютных элементов внутри

2023-11-28 09:17 UTC, pavlenkovit commented on src/components/MainPage.jsx
> +				<a href="#" className="restaurant__link">
Нужно ссылкой сделать всю карточку

<img width="407" alt="image" src="https://github.com/alisherbazhenov/calorie-content/assets/28729470/aa6e0884-c116-4193-977c-69bb5b83c932">

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +.restaurant__link::before {
Ты сделал через хак ссылку, но лучше сделать более простым вариантом и всю карточку обернуть в тег `a`

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +.item__array {
все эти свойства прям в svg лучше прописывай

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +.App {
Весь этот файлик нужно растащить по CSS модулям и после этого удалить App.css

2023-11-28 09:17 UTC, pavlenkovit commented on src/components/MainPage.jsx
> +			<img className="item__img" src={item.img} alt="" />
у тебя в данных есть alt, можно сюда подставить

2023-11-28 09:17 UTC, pavlenkovit commented on src/components/MainPage.jsx
> +function MainPage() {
лучше делай через const, а не через function. Так принято в большинстве проектов

```suggestion
const MainPage = () => {
```

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +	font-style: normal;
Писать дефолтные стили нет смысла. `font-style: normal `и `line-height: normal` можно удалить

2023-11-28 09:17 UTC, pavlenkovit commented on src/css/App.css
> +	margin-bottom: 20px;
лучше одной строкой

```suggestion
	margin: 0 0 20px;
```

2023-11-28 13:41 UTC, alisherbazhenov commented
Я внес необходимые корректировки

2023-11-28 13:46 UTC, alisherbazhenov commented
Я внес необходимые корректировки 
@pavlenkovit Можешь, пожалуйста, проверить?

2023-11-28 14:18 UTC, pavlenkovit requested changes
Еще буквально пару комментов

2023-11-28 14:18 UTC, pavlenkovit commented on src/app/App.js
> +	return (
Попробуй настроить IDE, чтобы было не два таба, а 2 пробела

```suggestion
  return (
```

2023-11-28 14:18 UTC, pavlenkovit commented on src/app/App.js
> +		</div>
если тебе не нужен этот div, а скорее всего он не нужен, то можно просто оставить пустые скобки, это не будет создавать доп узел 

```suggestion
		<>
			<MainPage />
			<Footer />
		</>
```

2023-11-29 09:22 UTC, pavlenkovit approved these changes

2023-11-29 09:22 UTC, pavlenkovit commented on src/components/footer/Footer.jsx
> +        <li className={styles.item}>
это не обязательно

Для таких штук можно делать отдельные массивчики с данными, а потом мапить

```
const items = [
  { id: 'home', icon: Home, href: '#' },
  ...
];
...
items.map(item => <li ...)
```

Тогда не нужно будет дублировать каждый раз инфу в трех местах в случае изменений в верстке

2023-11-30 12:44 UTC, merged